### ISSUE TITLE
Sharing related work from our lab at CMU!

### ISSUE THREAD

**Issue by linzhiqiu** [taolinzhang/BoostAdapter#1]
Great work! I just wanted to share some relevant work:

1 - [Multimodality Helps Unimodality: Cross-Modal Few-Shot Learning with Multimodal Models](https://arxiv.org/abs/2301.06267) for SOTA few-shot CLIP results
2 - [The Neglected Tails in Vision-Language Models](https://arxiv.org/abs/2401.12425) for SOTA zero-shot CLIP results.

**Comment by taolinzhang** [comment]
Thanks for sharing these relevant works!
